### ISSUE TITLE
Initial Roadmap

### ISSUE THREAD

**Issue by 223230** [223230/react_plug#1]
Really the bare essentials.

- Plugin
  - [x] Message (de-) serialization and communication
  - [x] Handling of parameter updates and Init
  - [x] Custom GUI messages
  - [ ] Editor as an `nih_plug` Editor (not a method)
  - [ ] XTask for TS codegen + building the UI
- UI
  - [ ] React project in `example`
  - [ ] Data structures for parameter config and state
  - [ ] [Context](https://react.dev/learn/passing-data-deeply-with-context) for plug-in data
    - [ ] Typed parameter values and setters
    - [ ] Message events
